platform :ios, '10'
#$RNFirebaseAsStaticFramework = true
#$FirebaseSDKVersion = '7.7.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


target 'AsuCare' do
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()
  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     if ['RNFBApp', 'RNFBMessaging', 'RNFBCrashlytics', 'RNFBDatabase'].include?(target.name)
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
  #     elsif target.name.eql?('RNFBAnalytics')
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseAnalytics'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleAppMeasurement'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'nanopb'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
  #     end
  #     if ['RNFBCrashlytics'].include?(target.name)
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Fabric'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'Crashlytics'})
  #       end
  #     if ['RNFBDatabase'].include?(target.name)
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'GoogleUtilities'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'FirebaseDatabase'})
  #       target.add_system_framework(installer.pods_project.targets.find{|target| target.name == 'leveldb'})
  #       end
  #   end
  # end
  # # pre_install do |installer|
  #   $static_frameworks = [
  #   'RNPermissions',  
  #   'Permission-LocationWhenInUse',
  #   'RNFBAnalytics',
  #   'RNFBAuth',
  #   'RNFBApp',
  #   'RNFBMessaging',
  #   'GoogleAppMeasurement'
  #   ]
  #   installer.pod_targets.each do |pod|
  #     if $static_frameworks.include?(pod.name)
  #       puts "Overriding the static_framework method for #{pod.name}"
  #       def pod.build_type;
  #         Pod::BuildType.static_library
  #      end
  #     end
  #   end
  # end
  # #post_install do |installer|
   # react_native_post_install(installer)
  #end
end
